name: CI Workflow

on:
  workflow_dispatch:

jobs:
  terraform-build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - name: Terraform Init
        run: terraform init
        working-directory: infra/

      - name: Terraform Validate
        run: terraform validate
        working-directory: infra/

      - name: Terraform Plan
        run: terraform plan
        working-directory: infra/

      - name: Terraform Apply
        run: terraform apply --auto-approve
        working-directory: infra/

      - name: Terraform Output
        run: terraform output -json > terraform_output.json
        working-directory: infra/

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r langgraph_requirements.txt

      - name: Register bot
        run: python telegram.py
